import { useEffect, useMemo, useState } from 'react'
import type { PosCatalogProductInputView, PosLoadDataView } from '@gadgets/workshop-shared/api'
import { useAuthenticatedApi } from './AuthContext'
import { resolveSalesScope } from './SalesPage'

const emptyProduct:PosCatalogProductInputView={name:'',priceMinor:0,kind:'product',saleEnabled:true,status:'active'}

export default function PosProductsPage(){
  const {authenticatedApi,businessSession}=useAuthenticatedApi(),scope=resolveSalesScope(businessSession)
  const [data,setData]=useState<PosLoadDataView|null>(null),[search,setSearch]=useState(''),[draft,setDraft]=useState<PosCatalogProductInputView|null>(null),[categoryName,setCategoryName]=useState(''),[busy,setBusy]=useState(false)
  const refresh=async()=>{if(scope)setData(await authenticatedApi.posLoadData(scope.organizationId,scope.companyId))}
  useEffect(()=>{void refresh()},[scope?.organizationId,scope?.companyId])
  const products=useMemo(()=>data?.products.filter(product=>[product.name,product.sku,product.barcode,product.category].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase()))??[],[data,search])
  if(!scope||!data)return <main className="grid min-h-full place-items-center">Cargando productos…</main>
  const edit=(product:PosLoadDataView['products'][number])=>setDraft({id:product.id,templateId:product.templateId,name:product.name,sku:product.sku,barcode:product.barcode,categoryId:data.catalog.categories.find(category=>category.name===product.category)?.id,priceMinor:product.priceMinor,taxId:data.catalog.taxes.find(tax=>tax.rateBasisPoints===product.taxBasisPoints)?.id,kind:'product',saleEnabled:true,status:'active'})
  return <main className="min-h-full bg-kumo-base">
    <header className="flex h-14 items-center gap-3 border-b border-kumo-line bg-kumo-elevated px-5"><a href="/pos" className="rounded-xl border border-kumo-line px-4 py-2">Punto de venta</a><span>Productos</span><span className="ml-auto"/><button onClick={()=>setDraft(emptyProduct)} className="rounded-xl bg-[#FE4A23] px-4 py-2 text-white">Nuevo</button></header>
    <div className="grid gap-0 lg:grid-cols-[1fr_340px]">
      <section className="p-5"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar productos…" className="mb-4 w-full rounded-xl border border-kumo-line bg-kumo-elevated p-3"/><div className="overflow-hidden rounded-xl border border-kumo-line">{products.map(product=><button key={product.id} onClick={()=>edit(product)} className="grid w-full grid-cols-[1fr_180px_140px] border-b border-kumo-line p-4 text-left hover:bg-kumo-line"><span>{product.name}<small className="block text-kumo-subtle">{product.sku||'Sin referencia'}</small></span><span>{product.category}</span><span className="text-right">{new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP'}).format(product.priceMinor)}</span></button>)}</div></section>
      <aside className="border-l border-kumo-line p-5"><h2 className="mb-4 text-xl">Categorías del PdV</h2><div className="mb-4 flex gap-2"><input value={categoryName} onChange={event=>setCategoryName(event.target.value)} placeholder="Nueva categoría" className="min-w-0 flex-1 rounded-xl border border-kumo-line p-3"/><button disabled={!categoryName||busy} onClick={async()=>{setBusy(true);await authenticatedApi.posSaveCategory(scope.organizationId,scope.companyId,{name:categoryName});setCategoryName('');await refresh();setBusy(false)}} className="rounded-xl border border-[#FE4A23] px-4 text-[#FE4A23]">Crear</button></div>{data.catalog.categories.filter(category=>category.status==='active').map(category=><div key={category.id} className="border-b border-kumo-line py-3">{category.name}</div>)}</aside>
    </div>
    {draft&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-5"><form onSubmit={async event=>{event.preventDefault();setBusy(true);await authenticatedApi.posSaveProduct(scope.organizationId,scope.companyId,draft);await refresh();setBusy(false);setDraft(null)}} className="grid w-full max-w-3xl gap-4 rounded-xl bg-kumo-elevated p-6 md:grid-cols-2"><h2 className="text-xl md:col-span-2">{draft.id?'Editar producto':'Nuevo producto'}</h2><label>Nombre<input required value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})} className="mt-2 w-full rounded-xl border border-kumo-line p-3"/></label><label>Referencia interna<input value={draft.sku??''} onChange={event=>setDraft({...draft,sku:event.target.value})} className="mt-2 w-full rounded-xl border border-kumo-line p-3"/></label><label>Código de barras<input value={draft.barcode??''} onChange={event=>setDraft({...draft,barcode:event.target.value})} className="mt-2 w-full rounded-xl border border-kumo-line p-3"/></label><label>Precio<input type="number" min="0" required value={draft.priceMinor} onChange={event=>setDraft({...draft,priceMinor:Number(event.target.value)})} className="mt-2 w-full rounded-xl border border-kumo-line p-3"/></label><label>Categoría<select value={draft.categoryId??''} onChange={event=>setDraft({...draft,categoryId:event.target.value||undefined})} className="mt-2 w-full rounded-xl border border-kumo-line p-3"><option value="">Productos</option>{data.catalog.categories.filter(category=>category.status==='active').map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Impuesto<select value={draft.taxId??''} onChange={event=>setDraft({...draft,taxId:event.target.value||undefined})} className="mt-2 w-full rounded-xl border border-kumo-line p-3"><option value="">Sin impuesto</option>{data.catalog.taxes.map(tax=><option key={tax.id} value={tax.id}>{tax.name}</option>)}</select></label><div className="flex gap-3 md:col-span-2"><button type="button" onClick={()=>setDraft(null)} className="flex-1 rounded-xl border border-kumo-line p-3">Descartar</button><button disabled={busy} className="flex-1 rounded-xl bg-[#FE4A23] p-3 text-white">Guardar</button></div></form></div>}
  </main>
}
