/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ContextRouteImport } from './routes/context'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as GatekeepersRouteImport } from './routes/gatekeepers'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as BlueprintIdRouteImport } from './routes/blueprint.$id'
import { Route as GadgetIdRouteImport } from './routes/gadget.$id'
import { Route as GatekeepersAppIdRouteImport } from './routes/gatekeepers_.$appId'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'
import { Route as ShareVaultTokenRouteImport } from './routes/share.vault.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersRoute = GatekeepersRouteImport.update({
  id: '/gatekeepers',
  path: '/gatekeepers',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintIdRoute = BlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GadgetIdRoute = GadgetIdRouteImport.update({
  id: '/gadget/$id',
  path: '/gadget/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersAppIdRoute = GatekeepersAppIdRouteImport.update({
  id: '/gatekeepers_/$appId',
  path: '/gatekeepers/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareVaultTokenRoute = ShareVaultTokenRouteImport.update({
  id: '/share/vault/$token',
  path: '/share/vault/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/blueprints': typeof BlueprintsRoute
  '/certificates': typeof CertificatesRoute
  '/collections': typeof CollectionsRoute
  '/context': typeof ContextRoute
  '/dispatch': typeof DispatchRoute
  '/explore': typeof ExploreRoute
  '/fiscal': typeof FiscalRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/sales': typeof SalesRoute
  '/signup': typeof SignupRoute
  '/vault': typeof VaultRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/share/vault/$token': typeof ShareVaultTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/blueprints': typeof BlueprintsRoute
  '/certificates': typeof CertificatesRoute
  '/collections': typeof CollectionsRoute
  '/context': typeof ContextRoute
  '/dispatch': typeof DispatchRoute
  '/explore': typeof ExploreRoute
  '/fiscal': typeof FiscalRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/sales': typeof SalesRoute
  '/signup': typeof SignupRoute
  '/vault': typeof VaultRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/share/vault/$token': typeof ShareVaultTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/blueprints': typeof BlueprintsRoute
  '/certificates': typeof CertificatesRoute
  '/collections': typeof CollectionsRoute
  '/context': typeof ContextRoute
  '/dispatch': typeof DispatchRoute
  '/explore': typeof ExploreRoute
  '/fiscal': typeof FiscalRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/sales': typeof SalesRoute
  '/signup': typeof SignupRoute
  '/vault': typeof VaultRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers_/$appId': typeof GatekeepersAppIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/share/vault/$token': typeof ShareVaultTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/billing'
    | '/blueprints'
    | '/certificates'
    | '/collections'
    | '/context'
    | '/dispatch'
    | '/explore'
    | '/fiscal'
    | '/gatekeepers'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/sales'
    | '/signup'
    | '/vault'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/workspace/$id'
    | '/share/vault/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/billing'
    | '/blueprints'
    | '/certificates'
    | '/collections'
    | '/context'
    | '/dispatch'
    | '/explore'
    | '/fiscal'
    | '/gatekeepers'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/sales'
    | '/signup'
    | '/vault'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
    | '/workspace/$id'
    | '/share/vault/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/billing'
    | '/blueprints'
    | '/certificates'
    | '/collections'
    | '/context'
    | '/dispatch'
    | '/explore'
    | '/fiscal'
    | '/gatekeepers'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/sales'
    | '/signup'
    | '/vault'
    | '/workspaces'
    | '/blueprint/$id'
    | '/gadget/$id'
    | '/gatekeepers_/$appId'
    | '/workspace/$id'
    | '/share/vault/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BillingRoute: typeof BillingRoute
  BlueprintsRoute: typeof BlueprintsRoute
  CertificatesRoute: typeof CertificatesRoute
  CollectionsRoute: typeof CollectionsRoute
  ContextRoute: typeof ContextRoute
  DispatchRoute: typeof DispatchRoute
  ExploreRoute: typeof ExploreRoute
  FiscalRoute: typeof FiscalRoute
  GatekeepersRoute: typeof GatekeepersRoute
  OutputsRoute: typeof OutputsRoute
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRoute
  SalesRoute: typeof SalesRoute
  SignupRoute: typeof SignupRoute
  VaultRoute: typeof VaultRoute
  WorkspacesRoute: typeof WorkspacesRoute
  BlueprintIdRoute: typeof BlueprintIdRoute
  GadgetIdRoute: typeof GadgetIdRoute
  GatekeepersAppIdRoute: typeof GatekeepersAppIdRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
  ShareVaultTokenRoute: typeof ShareVaultTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers': {
      id: '/gatekeepers'
      path: '/gatekeepers'
      fullPath: '/gatekeepers'
      preLoaderRoute: typeof GatekeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint/$id': {
      id: '/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/blueprint/$id'
      preLoaderRoute: typeof BlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gadget/$id': {
      id: '/gadget/$id'
      path: '/gadget/$id'
      fullPath: '/gadget/$id'
      preLoaderRoute: typeof GadgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers_/$appId': {
      id: '/gatekeepers_/$appId'
      path: '/gatekeepers/$appId'
      fullPath: '/gatekeepers/$appId'
      preLoaderRoute: typeof GatekeepersAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/vault/$token': {
      id: '/share/vault/$token'
      path: '/share/vault/$token'
      fullPath: '/share/vault/$token'
      preLoaderRoute: typeof ShareVaultTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BillingRoute: BillingRoute,
  BlueprintsRoute: BlueprintsRoute,
  CertificatesRoute: CertificatesRoute,
  CollectionsRoute: CollectionsRoute,
  ContextRoute: ContextRoute,
  DispatchRoute: DispatchRoute,
  ExploreRoute: ExploreRoute,
  FiscalRoute: FiscalRoute,
  GatekeepersRoute: GatekeepersRoute,
  OutputsRoute: OutputsRoute,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRoute,
  SalesRoute: SalesRoute,
  SignupRoute: SignupRoute,
  VaultRoute: VaultRoute,
  WorkspacesRoute: WorkspacesRoute,
  BlueprintIdRoute: BlueprintIdRoute,
  GadgetIdRoute: GadgetIdRoute,
  GatekeepersAppIdRoute: GatekeepersAppIdRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
  ShareVaultTokenRoute: ShareVaultTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
